apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik 
  tls:
  - hosts:
    - voting.app.com
    secretName: backend-tls
  rules:
  - host: voting.app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: votingapp
            port:
              number: 8080