apiVersion: v1
kind: Service
metadata:
  name: votingapp
  labels:
    app: votingapp
    service: votingapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: votingapp