apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
#    - type: string
#      containerResource:
#        container: string
#        name: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      external:
#        metric:
#          name: string
#          selector:
#            matchExpressions:
#              - key: string
#                operator: string
#                values:
#                  - string
#            matchLabels:  key: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      object:
#        describedObject:
#          apiVersion: string
#          kind: string
#          name: string
#        metric:
#          name: string
#          selector:
#            matchExpressions:
#              - key: string
#                operator: string
#                values:
#                  - string
#            matchLabels:  key: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      pods:
#        metric:
#          name: string
#          selector:
#            matchExpressions:
#              - key: string
#                operator: string
#                values:
#                  - string
#            matchLabels:  key: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      resource:
#        name: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-election
  type: io.k8s.api.autoscaling.v1.horizontalpodautoscalerspec
